tools:
  exceptions: "https://cb11258ddbc640f8a4a166bbfc218d27@o358880.ingest.sentry.io/4504765118414848"
  logging: https://service.us2.sumologic.com/ui/?appName=klear-frontend
  ci: "https://github.com/dcsil/klear-frontend/actions"

services:
  # production: https://klear.herokuapp.com

docs:
  getting_started: "https://github.com/dcsil/klear-frontend"

commands:
  bootstrap: "./script/bootstrap"
  database: "" # not relevant
  server: "npm run start"
  test: "npm run test"